### ISSUE TITLE
configuration-tools-0.2.12 test suite failure

### ISSUE THREAD

**Issue by peti** [alephcloud/hs-configuration-tools#40] opened 2015-02-22 16:06 UTC
The error messages seems quite extensive; please see http://hydra.cryp.to/build/578312/log/raw for a complete build log.

**Comment by larskuhtz** [comment] 2015-02-22 18:02
Thanks for the report, I'll take a look.

**Comment by larskuhtz** [comment] 2015-02-22 18:04
These are the failures in above test results:

```
WARNING: test tlsUrl-4 failed
WARNING: test tlsUrl-6 failed
WARNING: test tlsUrl-4 failed
WARNING: test tlsUrl-6 failed
```

**Comment by bennofs** [comment] 2017-02-18 11:36
These tests require networking (access to localhost at least). I don't think they will ever work in the  nix sandbox.

**Comment by bennofs** [comment] 2017-02-18 12:23
Ok I've investigated a little more and the issue is that `getent protocols` fails in the Nix sandbox. This issue is nothing that can be fixed in hs-configuration-tools, it is a Nix issue.

**Closed** 2017-09-12 16:45 UTC
